language: java
before_install:
 - cd ..
 - git clone https://github.com/wingLongitude/liger-data-access.git
 - cd liger-data-access
 - git checkout dev
 - mvn clean install
 - cd ..
 - git clone https://github.com/Canadensys/narwhal-processor.git
 - cd narwhal-processor
 - mvn install
 - cd ../canadensys-harvester
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6

